Error syncing the database: ConnectionError [SequelizeConnectionError]: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
    at ConnectionManager.connect (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:112:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:222:24)
    at async C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:174:32
    at async ConnectionManager.getConnection (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\dialects\abstract\connection-manager.js:197:7)
    at async C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\sequelize.js:305:26
    at async MSSqlQueryInterface.tableExists (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\dialects\abstract\query-interface.js:102:17)
    at async Employee.sync (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\model.js:939:21)
    at async Sequelize.sync (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\sequelize\lib\sequelize.js:377:9)
    at async initializeDB (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\config\db.js:19:5) {
  parent: ConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
      at Connection.socketError (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connection.js:1353:28)
      at C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connection.js:1146:14
      at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
    code: 'ESOCKET',
    [cause]: AggregateError: Could not connect (sequence)
        at connectInSequence (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connector.js:114:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connection.js:1129:20 {
      [errors]: [Array]
    }
  },
  original: ConnectionError: Failed to connect to 127.0.0.1:1433 - Could not connect (sequence)
      at Connection.socketError (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connection.js:1353:28)
      at C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connection.js:1146:14
      at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {
    code: 'ESOCKET',
    [cause]: AggregateError: Could not connect (sequence)
        at connectInSequence (C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connector.js:114:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async C:\Users\amartinez\Desktop\Encore Timesheet App\encore-ms-backend\node_modules\tedious\lib\connection.js:1129:20 {
      [errors]: [Array]
    }
  }
}


